### ISSUE TITLE
Subsequent position override messages toggle override on and off

### ISSUE THREAD

**Issue by nikipore** [rdmtc/node-red-contrib-sun-position#421] opened 2022-03-05 09:06 UTC
**Describe the bug**
Since I've upgraded (don't remember the prior version) the package to its current version 2.1.1, subsequent position override messages toggle the override of the blind control node on and off:

0. Initially, the blind position is set to `x` by a rule or by default. When there is a rule, the option to cancel manual override when the rule becomes active is *not* activated.
1. Sending a message `{"position": y}` into the node lets it the position to `y` (node status shows "y - overwritten [imp=0]").
2. Sending another message `{"position": y}` into the node lets it forget the override and yields the same behavior as step 0.
3. Sending another message `{"position": y}` into the node yields the same behavior as step 1.

And so forth: step n yields the same behavior as step n-2.

I tried to set `msg.resetOnSameValue` explicitly to `false` or `msg.ignoreSameValue` to `true`, but to no avail.

**Screenshots**
Will do when deemed necessary.

**Expected behavior**
The position override should remain active until it is explicitly reset by an incoming message or a rule with activated option "reset existing override when activated".

**System information (please complete the following information):**
 - Node Version 2.1.1
 - Node-Red Version 2.2.2

**Additional context**
A flow stripped down to the essential (without config node):
```
[{"id":"3d515f0d4a97f984","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[]},{"id":"33209c61675044f3","type":"blind-control","z":"3d515f0d4a97f984","name":"Test","topic":"","addIdType":"none","addId":"","positionConfig":"a962ddc.fbff22","autoTrigger":false,"autoTriggerTime":"1200000","startDelayTime":"10000","contextStore":"","results":[{"p":"","pt":"msgTopic","v":"","vt":"topic"},{"p":"","pt":"msgPayload","v":"","vt":"level"},{"p":"slat","pt":"msg","v":"","vt":"slat"},{"p":"blindCtrl","pt":"msg","v":"","vt":"ctrlObj"}],"blindIncrement":"0.05","blindOpenPos":"1","blindClosedPos":0,"blindPosDefault":"open (max)","blindPosDefaultType":"levelFixed","slatPosDefault":"","slatPosDefaultType":"none","overwriteExpire":"","rules":[],"sunControlMode":"0","sunFloorLengthType":"num","sunFloorLength":"0.3","sunMinDelta":"","blindPosMin":"25%","blindPosMinType":"levelFixed","blindPosMax":"open (max)","blindPosMaxType":"levelFixed","blindOpenPosOffset":"","blindClosedPosOffset":"","sunSlat":"","sunSlatType":"none","smoothTime":"","sunTopic":"","windowTopType":"num","windowTop":"2.01","windowBottomType":"num","windowBottom":"0.97","windowAzimuthStartType":"numAzimuth","windowAzimuthStart":"-50","windowAzimuthEndType":"numAzimuth","windowAzimuthEnd":"100","oversteers":[],"oversteerTopic":"","x":670,"y":220,"wires":[[],[]]},{"id":"bf2b6cf9e605ac4b","type":"inject","z":"3d515f0d4a97f984","name":"","props":[{"p":"position","v":"0.1","vt":"num"},{"p":"ignoreSameValue","v":"true","vt":"bool"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":510,"y":220,"wires":[["33209c61675044f3"]]},{"id":"47e3e9b95d772f92","type":"inject","z":"3d515f0d4a97f984","name":"","props":[{"p":"position","v":"0.1","vt":"num"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":510,"y":160,"wires":[["33209c61675044f3"]]},{"id":"d6354cc4c53d38b4","type":"inject","z":"3d515f0d4a97f984","name":"","props":[{"p":"position","v":"0.1","vt":"num"},{"p":"resetOnSameValue","v":"false","vt":"bool"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":510,"y":280,"wires":[["33209c61675044f3"]]}]
```

**Comment by Hypnos3** [comment] 2022-03-13 22:10
The problem is fixed in the latest version. `node-red-contrib-sun-position@2.2.0-beta`

Since this version has undergone some changes internally, I have this but still released as beta. That means you can't update it via Node-Red, but only via the command line.

**Comment by nikipore** [comment] 2022-03-13 22:30
Thanks! I am using Node-RED in Home Assistant (supervised docker image), but I figured out how to override the settings to use your package. A first test looks ok, no idea whether anything else has broken. Will let you know if that's the case. Please let me know in return when I'll be able to return to the standard release.

**Comment by hvorragend** [comment] 2022-03-13 23:17
Hallo Jan,

du kannst es in der Node Red-Konfiguration in Supervisor als zusätzliches npm-package hinzufügen. 

Viele Grüße
Carsten

**Comment by nikipore** [comment] 2022-03-14 09:35
Danke! Ja, genau das hatte ich gemeint und auch schon getan:
```yaml
npm_packages:
  - node-red-contrib-sun-position@2.2.0-beta
```
Und vorher das Add-On heruntergefahren und aus `config/node-red/package.json` das übers Node-RED installierte Standardpaket herausgenommen. (Deinstallieren übers GUI geht nicht, weil das Paket ja in Benutzung ist.)

**Comment by Hypnos3** [comment] 2022-03-14 20:51
Ich habe es mal mit in die Installationsanleitung aufgenommen:
https://github.com/rdmtc/node-red-contrib-sun-position/releases/tag/2.2.0-beta

**Comment by Hypnos3** [comment] 2022-03-14 20:54
Es wäre gut, wenn ihr berichten könnt, ob mit der neuen Version noch alles genauso läuft wie vorher.

**Comment by nikipore** [comment] 2022-03-14 21:33
Na klar, hatte ich oben ja schon versprochen. Bisher habe keine Auffälligkeiten gefunden. Vielleicht mache ich mir irgendwann mal die Arbeit, die Typos aus den Locales zu entfernen.

**Closed** 2022-03-22 20:38 UTC
Labels: 🐛 bug, ✓ already implemented
